# Generated by Django 5.0.6 on 2024-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
